# Args to simulate build from uswish
set("HUNTER_STATUS_DEBUG" "ON" CACHE INTERNAL "")
set("PORT" "JSCOnly" CACHE INTERNAL "")
set("ENABLE_JIT" "ON" CACHE INTERNAL "")
set("SHARED_CORE" "OFF" CACHE INTERNAL "")
set("ENABLE_TOOLS" "OFF" CACHE INTERNAL "")
set("ENABLE_API_TESTS" "OFF" CACHE INTERNAL "")
set("ENABLE_WEBCORE" "OFF" CACHE INTERNAL "")
set("ENABLE_WEBKIT" "OFF" CACHE INTERNAL "")
